// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoJ0h6WyiqcqYSHxI-9CZ3BDBD7AQyRyA',
    appId: '1:117361813391:web:443bc978e42f23f42ecdfa',
    messagingSenderId: '117361813391',
    projectId: 'excelerateapp-87687',
    authDomain: 'excelerateapp-87687.firebaseapp.com',
    storageBucket: 'excelerateapp-87687.firebasestorage.app',
    measurementId: 'G-ER9GQV4DSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXi1q7Jpw7FmBYw1NcCgumTMqZGFYsR_4',
    appId: '1:117361813391:android:83e1607d6bf49b7f2ecdfa',
    messagingSenderId: '117361813391',
    projectId: 'excelerateapp-87687',
    storageBucket: 'excelerateapp-87687.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxOajgv5NAY7L426iG64eRRVtYIckX7Ys',
    appId: '1:117361813391:ios:7ab817d7facae1ef2ecdfa',
    messagingSenderId: '117361813391',
    projectId: 'excelerateapp-87687',
    storageBucket: 'excelerateapp-87687.firebasestorage.app',
    iosBundleId: 'com.example.excelerateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxOajgv5NAY7L426iG64eRRVtYIckX7Ys',
    appId: '1:117361813391:ios:7ab817d7facae1ef2ecdfa',
    messagingSenderId: '117361813391',
    projectId: 'excelerateapp-87687',
    storageBucket: 'excelerateapp-87687.firebasestorage.app',
    iosBundleId: 'com.example.excelerateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoJ0h6WyiqcqYSHxI-9CZ3BDBD7AQyRyA',
    appId: '1:117361813391:web:443bc978e42f23f42ecdfa',
    messagingSenderId: '117361813391',
    projectId: 'excelerateapp-87687',
    authDomain: 'excelerateapp-87687.firebaseapp.com',
    storageBucket: 'excelerateapp-87687.firebasestorage.app',
    measurementId: 'G-ER9GQV4DSS',
  );
}
