import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'pages/login_page.dart';
import 'pages/program_home.dart';
import 'pages/sign_up.dart';
import 'pages/search_results.dart';
import 'pages/main_navigation.dart';
import 'providers/program_provider.dart';
import 'providers/theme_provider.dart';
import 'providers/user_provider.dart';
import 'pages/edit_profile.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Make sure this file exists (generated by flutterfire configure)

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ✅ Load saved login state
  final prefs = await SharedPreferences.getInstance();
  final isLoggedIn = prefs.getBool('isLoggedIn') ?? false;

  runApp(ExcelerateApp(isLoggedIn: isLoggedIn));
}

class ExcelerateApp extends StatelessWidget {
  final bool isLoggedIn;
  const ExcelerateApp({super.key, required this.isLoggedIn});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ProgramProvider()..fetchPrograms()),
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => UserProvider()),
      ],
      child: Consumer<ThemeProvider>(
        builder: (context, theme, _) {
          return MaterialApp(
            title: 'Excelerate',
            debugShowCheckedModeBanner: false,
            theme: ThemeData(
              brightness: Brightness.light,
              primarySwatch: Colors.orange,
              useMaterial3: true,
              scaffoldBackgroundColor: const Color(0xFFFDEBD0),
              iconTheme: const IconThemeData(color: Colors.black54),
            ),
            darkTheme: ThemeData(
              brightness: Brightness.dark,
              primarySwatch: Colors.orange,
              useMaterial3: true,
              scaffoldBackgroundColor: Colors.black,
              cardColor: const Color(0xFF121212),
              dialogTheme: const DialogThemeData(backgroundColor: Color(0xFF1E1E1E)),
              iconTheme: const IconThemeData(color: Colors.white70),
              appBarTheme: const AppBarTheme(
                backgroundColor: Color(0xFF1E1E1E),
                iconTheme: IconThemeData(color: Colors.white70),
              ),
              bottomNavigationBarTheme: const BottomNavigationBarThemeData(
                backgroundColor: Color(0xFF1E1E1E),
              ),
            ),
            themeMode: theme.isDarkMode ? ThemeMode.dark : ThemeMode.light,
            initialRoute: isLoggedIn ? '/home' : '/',
            routes: {
              '/': (context) => const LoginPage(),
              '/signup': (context) => const SignUpPage(),
              '/home': (context) => const MainNavigation(),
              '/program': (context) => const ProgramHome(),
              '/edit_profile': (context) => const EditProfilePage(),
              '/search': (context) => const SearchResultsPage(query: ''),
            },
          );
        },
      ),
    );
  }
}
